#+TITLE: Experiment for parallel quicksort
#+DATE: Tue Jan 12 17:34:21 CET 2016
#+AUTHOR: stanisic
#+MACHINE: winnetou
#+FILENAME: QuicksortData1.org
 
* MACHINE INFO
** PEOPLE LOGGED WHEN EXPERIMENT STARTED
stanisic :0           2016-01-12 10:41 (:0)
stanisic pts/13       2016-01-12 10:41 (:0)
stanisic pts/8        2016-01-12 10:55 (:0)
** ENVIRONMENT VARIABLES
LC_PAPER=en_US.UTF-8
XDG_VTNR=7
MANPATH=/home/stanisic/Repository/git-subrepo/man:/home/stanisic/Repository/git-subrepo/man:
XDG_SESSION_ID=c2
LC_ADDRESS=en_US.UTF-8
CLUTTER_IM_MODULE=xim
LC_MONETARY=en_US.UTF-8
SELINUX_INIT=YES
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/stanisic
SPACK_ROOT=/home/stanisic/Repository/spack
GPG_AGENT_INFO=/run/user/1000/keyring-LQaIJj/gpg:0:1
SHELL=/bin/bash
VTE_VERSION=3409
TERM=dumb
LC_NUMERIC=en_US.UTF-8
WINDOWID=60817420
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-LQaIJj
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1643
GTK_MODULES=overlay-scrollbar:unity-gtk-module
USER=stanisic
EMACS=t
LC_TELEPHONE=en_US.UTF-8
LS_COLORS=
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/1000/keyring-LQaIJj/ssh
TERMCAP=
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
COLUMNS=81
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
PATH=/home/stanisic/Repository/spack/bin:/home/stanisic/Repository/git-subrepo/lib:/home/stanisic/Repository/spack/bin:/home/stanisic/Repository/git-subrepo/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
DESKTOP_SESSION=ubuntu
QT_QPA_PLATFORMTHEME=appmenu-qt5
QT_IM_MODULE=ibus
LC_IDENTIFICATION=en_US.UTF-8
JOB=gnome-session
PWD=/home/stanisic/Repository/RR_example
XMODIFIERS=@im=ibus
LANG=en_US.UTF-8
GNOME_KEYRING_PID=1641
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
GDM_LANG=en_US
LC_MEASUREMENT=en_US.UTF-8
IM_CONFIG_PHASE=1
COMPIZ_CONFIG_PROFILE=ubuntu
PAPERSIZE=letter
GDMSESSION=ubuntu
SESSIONTYPE=gnome-session
XDG_SEAT=seat0
HOME=/home/stanisic
SHLVL=5
LANGUAGE=en_US:en
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
UPSTART_INSTANCE=
LOGNAME=stanisic
UPSTART_EVENTS=started starting
QT4_IM_MODULE=xim
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-QHwOvGyAKD
LESSOPEN=| /usr/bin/lesspipe %s
UPSTART_JOB=unity-settings-daemon
TEXTDOMAIN=im-config
INSTANCE=Unity
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
GTK_IM_MODULE=ibus
XDG_CURRENT_DESKTOP=Unity
INSIDE_EMACS=24.3.1,comint
LC_TIME=en_US.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
TEXTDOMAINDIR=/usr/share/locale/
COLORTERM=gnome-terminal
XAUTHORITY=/home/stanisic/.Xauthority
LC_NAME=en_US.UTF-8
_=/usr/bin/env
** HOSTNAME
winnetou
** MEMORY HIERARCHY
Machine (7936MB)
  Socket L#0 + L3 L#0 (6144KB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#4)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#1)
      PU L#3 (P#5)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
      PU L#4 (P#2)
      PU L#5 (P#6)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
      PU L#6 (P#3)
      PU L#7 (P#7)
  HostBridge L#0
    PCIBridge
      PCI 10de:0dfc
        GPU L#0 "card0"
    PCI 8086:1502
      Net L#1 "eth0"
    PCIBridge
      PCI 8086:422b
        Net L#2 "wlan0"
    PCI 8086:1e03
      Block L#3 "sda"
      Block L#4 "sr0"
** CPU INFO
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 1200.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 1200.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 1200.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 1200.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 2601.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 1200.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 1200.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x12
cpu MHz		: 1800.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5183.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

** CPU GOVERNOR
ondemand
** CPU FREQUENCY
1200000
** GPU INFO FROM NVIDIA-SMI

==============NVSMI LOG==============

Timestamp                           : Tue Jan 12 17:34:21 2016
Driver Version                      : 331.113

Attached GPUs                       : 1
GPU 0000:01:00.0
    Product Name                    : NVS 5200M
    Display Mode                    : N/A
    Display Active                  : N/A
    Persistence Mode                : Disabled
    Accounting Mode                 : N/A
    Accounting Mode Buffer Size     : N/A
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-3ded7c2d-5614-bf14-8240-563d786f7c69
    Minor Number                    : 0
    VBIOS Version                   : 70.08.A8.00.13
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x0DFC10DE
        Bus Id                      : 0000:01:00.0
        Sub System Id               : 0x05341028
        GPU Link Info
            PCIe Generation
                Max                 : N/A
                Current             : N/A
            Link Width
                Max                 : N/A
                Current             : N/A
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
    Fan Speed                       : N/A
    Performance State               : N/A
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 1023 MiB
        Used                        : 400 MiB
        Free                        : 623 MiB
    BAR1 Memory Usage
        Total                       : N/A
        Used                        : N/A
        Free                        : N/A
    Compute Mode                    : Default
    Utilization
        Gpu                         : N/A
        Memory                      : N/A
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        Gpu                         : 60 C
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
    Compute Processes               : N/A

** LINUX AND GCC VERSIONS
Linux version 3.13.0-61-generic (buildd@lgw01-50) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015
* CODE REVISIONS
** GIT REVISION OF REPOSITORY
commit 5fdf3dd65ffaf5309516cc194a757222d5250d21
Author: Luka Stanisic <luka.stanisic@imag.fr>
Date:   Tue Jan 12 17:33:55 2016 +0100

    Running second experiments through laboratory notebook
* COMPILATION
** COMPILATION OUTPUT
make: Entering directory `/home/stanisic/Repository/RR_example/src'
cc   -g -Wall -Wshadow -Wcast-align -Waggregate-return -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wpointer-arith -Wwrite-strings -finline-functions -O0 -pthread -lrt -std=c99  -c -o parallelQuicksort.o parallelQuicksort.c
cc   -g -Wall -Wshadow -Wcast-align -Waggregate-return -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wpointer-arith -Wwrite-strings -finline-functions -O0 -pthread -lrt -std=c99  parallelQuicksort.o  -o parallelQuicksort 
make: Leaving directory `/home/stanisic/Repository/RR_example/src'
** SHARED LIBRARIES DEPENDENCIES
	linux-vdso.so.1 =>  (0x00007ffd2b1c7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f358ac47000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f358a882000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f358ae65000)
* COMMAND LINE USED FOR RUNNING EXPERIMENT
./src/parallelQuicksort
* STDERR OUTPUT
* STDOUT OUTPUT
Array size: 9000000
Sequential quicksort took: 2.116776 sec.
Parallel quicksort took: 1.930489 sec.
Built-in quicksort took: 2.160452 sec.
Array size: 8811226
Sequential quicksort took: 2.142668 sec.
Parallel quicksort took: 1.996982 sec.
Built-in quicksort took: 2.075292 sec.
Array size: 8744419
Sequential quicksort took: 2.066043 sec.
Parallel quicksort took: 2.150883 sec.
Built-in quicksort took: 2.075714 sec.
Array size: 8811226
Sequential quicksort took: 2.089691 sec.
Parallel quicksort took: 2.056307 sec.
Built-in quicksort took: 2.103674 sec.
Array size: 8491341
Sequential quicksort took: 2.008246 sec.
Parallel quicksort took: 1.941752 sec.
Built-in quicksort took: 1.983505 sec.
Array size: 9000000
Sequential quicksort took: 2.102154 sec.
Parallel quicksort took: 1.988764 sec.
Built-in quicksort took: 2.109321 sec.
Array size: 6858418
Sequential quicksort took: 1.594093 sec.
Parallel quicksort took: 1.640847 sec.
Built-in quicksort took: 1.582843 sec.
Array size: 6858418
Sequential quicksort took: 1.623770 sec.
Parallel quicksort took: 1.731289 sec.
Built-in quicksort took: 1.708187 sec.
Array size: 8811226
Sequential quicksort took: 2.293278 sec.
Parallel quicksort took: 2.251948 sec.
Built-in quicksort took: 2.129549 sec.
Array size: 8491341
Sequential quicksort took: 2.045868 sec.
Parallel quicksort took: 2.228311 sec.
Built-in quicksort took: 1.995792 sec.
Array size: 8811226
Sequential quicksort took: 2.072011 sec.
Parallel quicksort took: 1.939599 sec.
Built-in quicksort took: 2.226636 sec.
Array size: 6000000
Sequential quicksort took: 1.497223 sec.
Parallel quicksort took: 1.366555 sec.
Built-in quicksort took: 1.365009 sec.
Array size: 6000000
Sequential quicksort took: 1.400419 sec.
Parallel quicksort took: 1.419141 sec.
Built-in quicksort took: 1.395582 sec.
Array size: 9000000
Sequential quicksort took: 2.135007 sec.
Parallel quicksort took: 2.035516 sec.
Built-in quicksort took: 2.116600 sec.
Array size: 9000000
Sequential quicksort took: 2.148016 sec.
Parallel quicksort took: 2.223957 sec.
Built-in quicksort took: 2.110557 sec.
Array size: 8744419
Sequential quicksort took: 2.082644 sec.
Parallel quicksort took: 1.967948 sec.
Built-in quicksort took: 2.053704 sec.
Array size: 6000000
Sequential quicksort took: 1.390926 sec.
Parallel quicksort took: 1.407396 sec.
Built-in quicksort took: 1.411550 sec.
Array size: 6858418
Sequential quicksort took: 1.585562 sec.
Parallel quicksort took: 1.711020 sec.
Built-in quicksort took: 1.618135 sec.
Array size: 8491341
Sequential quicksort took: 2.088940 sec.
Parallel quicksort took: 2.131112 sec.
Built-in quicksort took: 2.058102 sec.
Array size: 8491341
Sequential quicksort took: 2.039690 sec.
Parallel quicksort took: 2.087808 sec.
Built-in quicksort took: 2.019893 sec.
Array size: 6000000
Sequential quicksort took: 1.396565 sec.
Parallel quicksort took: 1.418453 sec.
Built-in quicksort took: 1.374275 sec.
Array size: 6858418
Sequential quicksort took: 1.622319 sec.
Parallel quicksort took: 1.544414 sec.
Built-in quicksort took: 1.578975 sec.
Array size: 8744419
Sequential quicksort took: 2.058773 sec.
Parallel quicksort took: 2.277069 sec.
Built-in quicksort took: 2.219328 sec.
Array size: 6000000
Sequential quicksort took: 1.391409 sec.
Parallel quicksort took: 1.448281 sec.
Built-in quicksort took: 1.373731 sec.
Array size: 8744419
Sequential quicksort took: 2.066387 sec.
Parallel quicksort took: 2.080458 sec.
Built-in quicksort took: 2.121395 sec.
Array size: 8744419
Sequential quicksort took: 2.091452 sec.
Parallel quicksort took: 1.971322 sec.
Built-in quicksort took: 2.079532 sec.
Array size: 8811226
Sequential quicksort took: 2.073895 sec.
Parallel quicksort took: 2.162771 sec.
Built-in quicksort took: 2.048615 sec.
Array size: 6858418
Sequential quicksort took: 1.549181 sec.
Parallel quicksort took: 1.608081 sec.
Built-in quicksort took: 1.613563 sec.
Array size: 8491341
Sequential quicksort took: 2.010737 sec.
Parallel quicksort took: 1.913945 sec.
Built-in quicksort took: 1.988795 sec.
Array size: 9000000
Sequential quicksort took: 2.138983 sec.
Parallel quicksort took: 2.057988 sec.
Built-in quicksort took: 2.154890 sec.
* ELAPSED TIME FOR RUNNING THE PROGRAM
Elapsed:    175.584874456 seconds
